#!/bin/sh

# Submit customer release script: mark a customer release from a pair of release candidate packages
# - tag the release commit
# - bump the visible version
# - commit as visible version change (so all new builds are candidates for the next version)
# - push tags

# Don't allow using unset vars (-u)
set -o nounset
# Exit on error (-e)
set -o errexit

mvers=$1
if [ "$mvers" == "" ]; then
	echo "Please supply the next marketing version"
	exit
fi

version=`agvtool mvers -terse1`
buildnumber=`agvtool vers -terse`

# Tag the release
git tag -m "Release $version build $buildnumber" -a Release-${version}

# Prepare for the next release
agvtool new-marketing-version $mvers
git commit -a -m "Start dev cycle for version $mvers"

#git push
git push --tags
